### ISSUE TITLE
make test doesn't work

### ISSUE THREAD

**Issue by comiquita** [giggls/osml10n#23]
Hello,

Running on ubuntu 22.04

During installation, when I run make test, I get the following error. 

`$ sudo make test
[sudo] password for alexander: 
cd lua_osml10/tests/ && ./runtests.lua
/usr/bin/lua: ./osml10n/geo_transcript.lua:10: Can not connect to server 127.0.0.1:8033. Is geo-transcript-srv.py running?
stack traceback:
	[C]: in function 'error'
	./osml10n/geo_transcript.lua:10: in main chunk
	[C]: in function 'require'
	./osml10n/init.lua:4: in local 'import'
	./osml10n/init.lua:13: in main chunk
	[C]: in function 'require'
	./osml10n.lua:1: in main chunk
	[C]: in function 'require'
	./runtests.lua:6: in main chunk
	[C]: in ?
make: *** [Makefile:31: test] Error 1
`
I'd appreaciate if anybody can help me.

**Comment by giggls** [comment]
Did you install the Debian packages?

**Comment by comiquita** [comment]
I ended up having the same issues already raised in [https://github.com/giggls/osml10n/issues/19](url). So that helped move forward.

Right now, after starting the server like this:
`/usr/bin/geo-transcript-srv.py -s -g /usr/share/osml10n/boundaries`

I get:
`Loading osml10n transcription server: ready.`

I open another terminal and cd to /osml10n and type make test. All tests pass ending in a line as follows:
`87 tests passed, 0 tests failed.`

However, the server spits out errors througout when tests are running:

`--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/usr/bin/geo-transcript-srv.py", line 275, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/geo-transcript-srv.py", line 248, in handle_connection
    reply = tc.transcript(id,cc,name)
  File "/usr/bin/geo-transcript-srv.py", line 149, in transcript
    return(cantonese_transcript(unistr))
  File "/usr/bin/geo-transcript-srv.py", line 93, in cantonese_transcript
    transcript=pinyin_jyutping_sentence.jyutping(st, spaces=True)
  File "/home/alexander/.local/lib/python3.10/site-packages/pinyin_jyutping_sentence/__init__.py", line 390, in process_sentence_jyutping
    return self.process_sentence(sentence, self.conversion_data.jyutping_word_map, self.conversion_data.jyutping_char_map, self.decode_jyutping, tone_numbers, spaces, remove_tones)
  File "/home/alexander/.local/lib/python3.10/site-packages/pinyin_jyutping_sentence/__init__.py", line 379, in process_sentence
    word_list = list(seg_list)
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 325, in cut
    for word in cut_block(blk):
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 250, in __cut_DAG
    DAG = self.get_DAG(sentence)
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 181, in get_DAG
    self.check_initialized()
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 170, in check_initialized
    self.initialize()
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 113, in initialize
    default_logger.debug("Building prefix dict from %s ..." % (abs_path or 'the default dictionary'))
Message: 'Building prefix dict from the default dictionary ...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/usr/bin/geo-transcript-srv.py", line 275, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/geo-transcript-srv.py", line 248, in handle_connection
    reply = tc.transcript(id,cc,name)
  File "/usr/bin/geo-transcript-srv.py", line 149, in transcript
    return(cantonese_transcript(unistr))
  File "/usr/bin/geo-transcript-srv.py", line 93, in cantonese_transcript
    transcript=pinyin_jyutping_sentence.jyutping(st, spaces=True)
  File "/home/alexander/.local/lib/python3.10/site-packages/pinyin_jyutping_sentence/__init__.py", line 390, in process_sentence_jyutping
    return self.process_sentence(sentence, self.conversion_data.jyutping_word_map, self.conversion_data.jyutping_char_map, self.decode_jyutping, tone_numbers, spaces, remove_tones)
  File "/home/alexander/.local/lib/python3.10/site-packages/pinyin_jyutping_sentence/__init__.py", line 379, in process_sentence
    word_list = list(seg_list)
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 325, in cut
    for word in cut_block(blk):
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 250, in __cut_DAG
    DAG = self.get_DAG(sentence)
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 181, in get_DAG
    self.check_initialized()
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 170, in check_initialized
    self.initialize()
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 146, in initialize
    default_logger.debug(
Message: 'Dumping model to file cache /tmp/jieba.cache'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/usr/bin/geo-transcript-srv.py", line 275, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/geo-transcript-srv.py", line 248, in handle_connection
    reply = tc.transcript(id,cc,name)
  File "/usr/bin/geo-transcript-srv.py", line 149, in transcript
    return(cantonese_transcript(unistr))
  File "/usr/bin/geo-transcript-srv.py", line 93, in cantonese_transcript
    transcript=pinyin_jyutping_sentence.jyutping(st, spaces=True)
  File "/home/alexander/.local/lib/python3.10/site-packages/pinyin_jyutping_sentence/__init__.py", line 390, in process_sentence_jyutping
    return self.process_sentence(sentence, self.conversion_data.jyutping_word_map, self.conversion_data.jyutping_char_map, self.decode_jyutping, tone_numbers, spaces, remove_tones)
  File "/home/alexander/.local/lib/python3.10/site-packages/pinyin_jyutping_sentence/__init__.py", line 379, in process_sentence
    word_list = list(seg_list)
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 325, in cut
    for word in cut_block(blk):
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 250, in __cut_DAG
    DAG = self.get_DAG(sentence)
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 181, in get_DAG
    self.check_initialized()
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 170, in check_initialized
    self.initialize()
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 164, in initialize
    default_logger.debug(
Message: 'Loading model cost 0.375 seconds.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/usr/bin/geo-transcript-srv.py", line 275, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/geo-transcript-srv.py", line 248, in handle_connection
    reply = tc.transcript(id,cc,name)
  File "/usr/bin/geo-transcript-srv.py", line 149, in transcript
    return(cantonese_transcript(unistr))
  File "/usr/bin/geo-transcript-srv.py", line 93, in cantonese_transcript
    transcript=pinyin_jyutping_sentence.jyutping(st, spaces=True)
  File "/home/alexander/.local/lib/python3.10/site-packages/pinyin_jyutping_sentence/__init__.py", line 390, in process_sentence_jyutping
    return self.process_sentence(sentence, self.conversion_data.jyutping_word_map, self.conversion_data.jyutping_char_map, self.decode_jyutping, tone_numbers, spaces, remove_tones)
  File "/home/alexander/.local/lib/python3.10/site-packages/pinyin_jyutping_sentence/__init__.py", line 379, in process_sentence
    word_list = list(seg_list)
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 325, in cut
    for word in cut_block(blk):
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 250, in __cut_DAG
    DAG = self.get_DAG(sentence)
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 181, in get_DAG
    self.check_initialized()
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 170, in check_initialized
    self.initialize()
  File "/home/alexander/.local/lib/python3.10/site-packages/jieba/__init__.py", line 166, in initialize
    default_logger.debug("Prefix dict has been built successfully.")
Message: 'Prefix dict has been built successfully.'
Arguments: ()
`
are this "normal"/expected errors?... I'm going to check if another issue has been raised previously.

**Comment by giggls** [comment]
You should not need to start the Server manually, the Debian package should do this for you.
Unfortunately I can not reproduce this easily as I do not use ubuntu. Will try to check this inside a chroot.

**Comment by giggls** [comment]
OK, I can reproduce this in my Ubuntu 22.04 chroot.
Looks like this stderr redirection hack no longer works in Python 3.10
Does not seem to harm functionality though.
I will see what I can do.

**Comment by comiquita** [comment]
Thank you for looking into it.
